version: "3"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=lct
      - MYSQL_ROOT_PASSWORD=localdbpass # Change in production!
    ports:
      - '3306:3306'

  server:
    build: server/
    restart: unless-stopped
    command: npm run start:prod
    ports:
      - "5000:80"
    depends_on:
      - db

  client:
    container_name: client
    build: client/
    ports:
      - "3000:80"
    depends_on:
      - server

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      CLIENT: "client:80"
      SERVER: "server:80"
      PORT: "80"
    depends_on:
      - client
      - server